[[shortcuts]]
name = "Post Update"
path = "update"

[activitypub]
domain = "archival.dev"
username = "archival"
follow = ["@bsky.brid.gy@bsky.brid.gy", "@threads@threads.net"]

[activitypub.actor]
object = "home"
summary = "description"
icon = "logo"

[activitypub.objects.update]
featured = "pinned"
name = "title"
content = "body"
published = "publish_date"
